### ISSUE TITLE
Enhancement: Design a better looking page

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#1]
This page isn't nearly spooky enough! I'm open to ideas on a better layout, design, colors, etc. 

Preferably, I'd like to keep using the Bootstrap framework.

**Comment by mathagician** [comment]
@scrabill I have some suggestions. 

Text **Powered by Boo-t-strap, Javascript and Spookiness!** at the bottom.
Also, a counter can be put which should change the theme of page on daily basis
Adding a background video would be a nice thing to have.
 and update the libraries like bootstrap, jquery with latest versions.

**Comment by paniya** [comment]
Hi like to contribute!
I do have page with me!
can please add me so i can push them

**Comment by altruisticnarcissist** [comment]
Hi, I would like to help!

**Comment by scrabill** [comment]
@mathagician @paniya @altruisticnarcissist 

Hi everyone! Thank for putting up with delays--this project got way more responses then I was expecting. 

I'm going through commits in order (oldest to newest) and there have been a few other contributions. The bootstrap / jquery libraries should be up to date but changes to the overall layout, colors, etc, are still welcome.
