### ISSUE TITLE
Fix: Broken CSS declaration block

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#120]
I was wondering why a recent addition to the styles.css wasn't rendering.

While resolving merge conflicts, I accidentally deleted the second to the last closing curly bracket. 

What I have is this:
```
#splashText {
	font-size: 40px;

.text-large {
	font-size: 20px !important;
}
```

And it should be this:
```
#splashText {
	font-size: 40px;
}
.text-large {
	font-size: 20px !important;
}
```

Simple fix. Perfect for a beginner or first timer

**Comment by anthonyjuan** [comment]
Hi, I've changed it  #121
