### ISSUE TITLE
Documentation: Add link to contributor graph to the contributer-list.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#123]
In the first few weeks of this project, I did not have a contributer-list.md

To save a little time from having to go back and adding early contributor manually, we can cheat a bit and add a link to the insights page for this repository. 

For this issue, I'd suggest adding something like this to the bottom of the contributer-list.md file:

`[And many more!](https://github.com/scrabill/how-many-days-until-halloween/graphs/contributors)`

**Comment by royalmitten** [comment]
Hi, added the link in #126 :)
