### ISSUE TITLE
Delete rouge ":" file

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#147]
Not sure how [this](https://github.com/scrabill/how-many-days-until-halloween/blob/master/:) got here, but it can be deleted. 

Super easy issues. Great for first-timers :)

**Comment by MitchB09** [comment]
I can pick this up. looking to get my first thing done for hactoberfest

**Comment by Sagar1711** [comment]
Hi,
I can pick this up looking for a project to contribute for the first time. I really want to contribute to an open source project.
Thanks

**Comment by scrabill** [comment]
This is closed by pull request #149
