### ISSUE TITLE
Documentation: Improve CONTRIBUTING.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#148]
I copied last year [CONTRIBUTION.md](https://github.com/scrabill/how-many-days-until-halloween/blob/master/CONTRIBUTING.md) document, which can be improved on. 

It would be nice to include dependencies, exact steps on how to fork this repo, etc to make this more user-friendly. 

I'm open to ideas on this one.

**Comment by naufaldi** [comment]
I'll take this one, may be try to add "how to fork this repo"

**Comment by yatri1609** [comment]
@scrabill I would like to work on this issue. Can I?
