### ISSUE TITLE
URl with problems

### ISSUE THREAD

**Issue by mizamelo** [scrabill/how-many-days-until-halloween#163]
The url http://shannoncrabill.com/how-many-days-until-halloween/ is a problem.

**Comment by scrabill** [comment]
Can you elaborate? How is it a problem?

**Comment by scrabill** [comment]
@mizamelo @stufinn

Good find. If there isn't already a PR fix for this, either of you are welcome to make that correction

**Comment by scrabill** [comment]
The video link that was originally added can be found here #152
