### ISSUE TITLE
Enhancement: Add sheilds to README.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#174]
I'd like to add some shields to make some information easier to spot on the README.md. 

Looking at what is available at [Sheilds.io](https://shields.io/#/examples/other), these are the shields that I think are best suited for this project.

* GitHub commit activity the past week, 4 weeks, year
￼* GitHub last commit

[freeCodeCamp](https://github.com/freeCodeCamp/freeCodeCamp) is a good example of a repo that uses some custom and pre-built shields

Open to discussion and suggestions for additional or custom shields.

**Comment by Nerph** [comment]
I'll give this a go!

**Comment by yatri1609** [comment]
Is this still open @scrabill ? If so I would like to work on this issue

**Comment by scrabill** [comment]
@yatri1609

If there's another shield that you think would be useful, feel free to add it!

**Comment by lacexd** [comment]
is it still open?
