### ISSUE TITLE
Documentation: ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#175]
The purpose of an issue template is to guide Githubbers in providing detailed information when creating a new issue. 

The main information I would like this issue template to include is as follows

* **Description of the feature, request or problem.** Be specific. If it is a bug, what happened? What were you expecting to happen? If you are looking to make an improvement, outline what you are suggesting and how it might be achieved. You do not know how exactly to solve a problem or how to implement a new feature, but an idea can help to get the information started. 

Here is an example of an issue template
https://github.com/thepracticaldev/dev.to/blob/master/.github/ISSUE_TEMPLATE.md

Ours does not need to be that detailed but think about what information you would like to know as a maintainer or would be helpful for contributors to know.

**Comment by tonytheleg** [comment]
Hello, are you basically just looking for a markdown file with instructions on what to include for submitting bugs essentially? I think I can manage that!

**Comment by naufaldi** [comment]
hello, i will try to provide making template for issue template. May be try about feature and problem template.
