### ISSUE TITLE
Documentation: PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#178]
The purpose of a pull request template is to guide Githubbers in providing detailed information when opening a pull request. A template can help answer commonly asked questions, provide guidance and help to maintain a quality codebase.

The main information I would like the pull request template to include is as follows

* Descriptive name. Your pull request should have a descriptive name.

* Has this feature already been added? Sometimes, duplicate pull requests happen. It's worth checking the [pull requests](https://github.com/scrabill/how-many-days-until-halloween/pulls) and [issue page](https://github.com/scrabill/how-many-days-until-halloween/issues) to see if the change you are requesting has already been made. 

* Description of the change being made. It's helpful to outline what changes were made to which files so that I have an idea of what will be involved in reviewing the code and—hopefully—merging it into the codebase. 

* Issue number. If your pull request is related to a specific issue, included it in your description and or pull request name. It helps to keep changes linked. Any issues that are referenced in pull requests become part of the discussion history of the issue.

Here is an example of a pull request template
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Ours does not need to be that detailed but think about what information is helpful for both the contributor and maintainer to know.

**Comment by vincentt117** [comment]
Hi, I'd like to work on this issue. Could you assign it to me? Thanks!

**Comment by scrabill** [comment]
I'm noticing while the current pull request template has fields that are helpful and could be relevant, they are mostly being submitting as blank or incomplete. Not the end of the world since the PR title usually tells me what I need to know. The long pull request template _might_ be intimidating for new coders, so I'd like to shorten to be no more than 1-2 paragraphs. 

Open to discussions on this.

The main points I'd like to get across are as follows.

- Please name your PR something descriptive
- Add additional information in the body of your pull request (what changes you made, to which files, etc)
- Reference an issue number (if there is one)
- Be aware of duplicate pull requests that resolve the same issue
