### ISSUE TITLE
Documentation: CHANGELOG.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#179]
We need a changelog. [Last year](https://github.com/scrabill/how-many-days-until-halloween/blob/2017/CHANGELOG.md), I did a manual changelog to document what features are added over time. Recently discovered that there are ways to auto-generate changelogs based on your issues and commits. 

This is the example I found: https://github.com/github-changelog-generator/github-changelog-generator

Is someone is interested in giving this a try, post here and let's chat

**Comment by cajuuh** [comment]
we use [commitizen](http://commitizen.github.io/cz-cli/) at work, see if it matches your specs if you want i could take care of implementation
