### ISSUE TITLE
Enhancement: Improve Rendering for Mobile Devices

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#188]
## I'm submitting a...
<pre><code>
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

On smaller screens (simulated in a browser window) the spooky text is really small and everything seems squashed at the top of the screen. The default CSS can be tweaked so that there is a better visual for anyone viewing this on a mobile device.

For example

![screen shot 2018-10-05 at 9 42 37 pm](https://user-images.githubusercontent.com/17805262/46566196-fc423c80-c8e7-11e8-84d1-b4c6a9defb30.png)

## Expected behavior

Larger text on mobile. Assets take up more of the mobile device real estate

## If this is a feature request please fill out the following:
<pre><code>
As a (user, developer, contributor, etc): User
I want: Better read the text on screen
So that: I know how many days there are until Halloween 🙃

</code></pre>

## Environment
<pre><code>
Browser:
- [ ] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by bereninga** [comment]
I'd like to take this on.

**Comment by scrabill** [comment]
@bereninga Go for it

**Comment by bereninga** [comment]
@scrabill I've created a PR for this change. Let me know if I might've misunderstood the task.

**Comment by thevenice** [comment]
I have done a PR for changes , i added  dynamic sizing for fonts to adjust on any size of device for this issue + added a suggestion  for new features ideas too.
