### ISSUE TITLE
Bug: Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#190]
About halfway down, the Hacktoberfest link is broken.

This is what is there currently

`
Make sure you are registered for the [HacktoberFest] before you start!(https://hacktoberfest.digitalocean.com/)

`

**Comment by amrs-tech** [comment]
@scrabill I'll try to fix it

**Comment by amrs-tech** [comment]
Please review my PR and merge if it's okay :)

**Comment by scrabill** [comment]
Thanks! Your fix has been merged
