### ISSUE TITLE
Documentation: Add contributor page

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#20]
It may be nice to have a page where all contributors to this repo can add include their username and link to their Github page. 

If someone wants to tackle this, here is an example
- [HacktoberFest-Census](https://github.com/scrabill/Hacktoberfest-Census)

If you are a first-time git contributor, message me and I can help you get this set up. Feel free to ask questions below.

**Comment by hoffmanjoshua** [comment]
I can work on this!

**Comment by paniya** [comment]
I can help you
