### ISSUE TITLE
Documentation: Remove or Update "New features" link from CONTRIBUTING.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#205]
## This request is for 
[x] Beginners
[x] First Timers
[x] Non-Coders (Markdown knowledge needed)

## I'm submitting a...
<pre><code>
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## Current behavior

Currently, the [New features](https://github.com/scrabill/how-many-days-until-halloween/issues/1) link on [CONTRIBUTING.md](https://github.com/scrabill/how-many-days-until-halloween/blob/master/CONTRIBUTING.md) (line 32, as of this writing) links to the very first issue I created last year. This doesn't work anymore as that issue has been closed (it was made for the 2017 version / branch) and there are no uses of a tag named "New Features"

## Expected behavior

I think this link should either be removed entirely or replaced with a link to a different issue label

For example, 

Instead of this
```
[New features](https://github.com/scrabill/how-many-days-until-halloween/issues/1)
```

Something like this
```
[Discussion](https://github.com/scrabill/how-many-days-until-halloween/issues?q=is%3Aissue+is%3Aopen+label%3Adiscussion)
```

Other examples would be to link to the Hacktoberfest tag

## Important

Before you make a pull request, please comment on issue that you would like to work on it. That way, we can avoid duplicate PRs and a first-timer can work on this.

**Comment by eharris99** [comment]
hi I will take care of this
