### ISSUE TITLE
Enhancement: Add Fork me on Github Ribbon OR Github Corner

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#207]
## This request is for

[x] Beginners
[x] First Timers
[x] Intermediate (If you want to do any customizations)
[] Non-Coders (Markdown knowledge needed)
[x] Coders (Some HTML knowledge may be needed)

## I'm submitting a...

[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request

I've been wondering where people were getting those cool [Github Corner](https://github.com/tholman/github-corners) or [Fork me on Github](https://blog.github.com/2008-12-19-github-ribbons/) ribbons. Now that I've found them, I think it would be nice to add one or the other (or both?) to the How Many Days Until Halloween Page

## Steps

1. Pick a badge option (I'm open to suggestions on this)
2. Add it to the site
3. Also, add a reference to it in the technologies section of the README.md document

**Comment by eharris99** [comment]
I will do this
