### ISSUE TITLE
Bug: Countdown logic is off by 1

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#218]
This request is for
[x] Beginners (maybe, this will take some debugging)
[x] First Timers
[x] Coders

## I'm submitting a...
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request

## Current behavior

Today is Wednesday, October 24. Halloween is next Wednesday, which should be 7 days away. Currently, the countdown timer is saying it is 6 days away. 31-24 _should_ be 7 days away.

![screen shot 2018-10-24 at 9 21 02 pm](https://user-images.githubusercontent.com/17805262/47470210-bf74b180-d7d2-11e8-91c8-d31b74d02235.png)

## Expected behavior

Update logic to correctly count the days left until the 31st

**Comment by lnchapin** [comment]
I can do this

**Comment by StevePaytosh** [comment]
similar solution as tagpro applied.

https://github.com/scrabill/how-many-days-until-halloween/pull/220
