### ISSUE TITLE
Enhancement: Add a Halloween fact

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#226]
@brandonstinson added a list of [random Halloween facts](https://github.com/scrabill/how-many-days-until-halloween/pull/170) that generate on page load. 

The facts (strings) are stored in a facts array. Adding a new item to this array is an easy, first-timer-friendly pull request. 

- Within script.js, look for the comment `// Array of Halloween facts`.
- Add a new fact to the facts array (try to keep them 1-2 lines long)
- Open a pull request with your new fact(s) and I'll get them added in. 

Reach out if you have any questions. 

Edit: Wow, there's been an explosion of pull requests relating to this template in the past 12 hours! To keep this array and JS file from getting out of hand, please limit your facts to no more than 3 lines total.

**Comment by shoutoutloud** [comment]
Hi, can I help with this issue.

**Comment by jonathanfrancisco** [comment]
#232

**Comment by jonathanfrancisco** [comment]
#232

**Comment by Scriptle** [comment]
#255

**Comment by chansen17** [comment]
Super old! But is it still cool to add a Holloween fact!? For practice sake, thanks. D;
