### ISSUE TITLE
Enhancement: Add Halloween Costume Ideas

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#253]
@stufinn added a feature that will randomly generate a new [Halloween custom idea](https://github.com/scrabill/how-many-days-until-halloween/pull/202). 

Adding a new costume idea is a very easy addition that is beginner or first-timer friendly. 

- Open scripts.js and look for `// Script for Random Costume Picker`
- Add an object to the `costumes` array with the costume name and a link to an image (or tutorial) in the following format
 
 ```
 ["Octocat", "https://twitter.com/ryanlanciaux/status/659415196058918912"],
 ```

- Please keep your suggested customs PG / SFW
- Include a source for your custom in your pull request if you can
- Limit costume additions to three to help keep the array from getting too long

Reach out if you have a question

**Comment by stufinn** [comment]
Thanks for adding this! I agree that's a great idea for a good first issue.

**Comment by rjdoughty** [comment]
#272

**Comment by rjdoughty** [comment]
#272  **Added incredibles costume idea line 205 issue 253** #272 #

**Comment by rjdoughty** [comment]
#272 Added incredibles costume idea line 205 issue 253 #

**Comment by leighdamico** [comment]
Is it still possible to contribute on this issue or was it exclusively for Hacktoberfest?
