### ISSUE TITLE
Documentation: Check spelling on CONTRIBUTING.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#26]
There are a few typos and misspellings on the CONTRIBUTING.md page. 

I'm reserving this issue for any first-timers or code newbies who want to practice using git and making pull requests. 

If you need help comment below and I'll help you to get started!

**Comment by jameslave** [comment]
I can do that. 👍

**Comment by tomasswood** [comment]
Happy to do this one, let me know :)

**Comment by Jared-Peacock** [comment]
I've never made a pull request and would like to start here - please choose me! :)

**Comment by scrabill** [comment]
@Jared-Peacock @tomasswood 

It looks like someone else already made this edits. I'm sure there are other errors elsewhere if you wanted to take a look.
