### ISSUE TITLE
The Website Isn't Up-To-Date

### ISSUE THREAD

**Issue by Scriptle** [scrabill/how-many-days-until-halloween#292]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The recent costume ideas and facts aren't implemented on the website.

## Expected behavior

The recent costume ideas and facts should be implemented on the website.

## If this is a feature request please fill out the following:

<pre><code>
As a (user, developer, contributor, etc):
I want:
So that:

</code></pre>

## Environment

<pre><code>
Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by scrabill** [comment]
@Scriptle 

The updates from the repo to the website are not automated. It's just me working on this, but I plan on pushing more updates to the site tonight

**Comment by Scriptle** [comment]
Oh right. Keep up the good work :)
