### ISSUE TITLE
Enhancement: Add link to github repo to index.html

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#3]
Similar to the [footnote on this page](http://shannoncrabill.com/pay-day/) add a link to the Github repo to the index.html page

1. Fork the repo
2. Download all files
3. Open Index.html
4. Add the following (or something similar) to the end of the <p> starting with "Powered by.."

`Fork this on <a href="https://github.com/scrabill/how-many-days-until-halloween">Github</a>`

6. Commit change
7. Open a pull request

Questions can be asked here

**Comment by scrabill** [comment]
@Jared-Peacock

It looks like this edit got overwritten in a recent update. You're welcome to add it back in again.

**Comment by RudyB** [comment]
Check #37
