### ISSUE TITLE
BugFix: Fix a typography error in the website's footer

### ISSUE THREAD

**Issue by duyphaphach** [scrabill/how-many-days-until-halloween#319]
## I'm submitting a...

<pre><code>
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

The website footer contains a typography error
![image](https://user-images.githubusercontent.com/40330059/51801936-eda4da00-2276-11e9-87e3-fc35ce038e4c.png)

## Expected behavior
The text should be `Bootstrap`
## Environment

<pre><code>
Browser:
- [X] Chrome (desktop) version 71
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by vansosnin** [comment]
Done :)

**Comment by scrabill** [comment]
I'm closing this issue since this is part of the 2018 build
