### ISSUE TITLE
Documentation: Comment all of the things!

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#32]
The code for this project has changed dramatically since I first pushed it to Github last week.

But it's also not 100% clear on what does what (I'm looking at you [script.js](https://github.com/scrabill/how-many-days-until-halloween/blob/master/js/script.js))

This is a bigger issue that may need to be broken into chunks.

I'd like to see commenting around functions outlining what they do, what does what to (hopefully) avoid duplicate effort and merge errors in the future.

**Comment by nbuss848** [comment]
I can start some documentation why not
