### ISSUE TITLE
Enhancement: Migrate the facts and costumes array to different javascript files

### ISSUE THREAD

**Issue by gabLaroche** [scrabill/how-many-days-until-halloween#326]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## If this is a feature request please fill out the following:

<pre><code>
As a contributor:
I want to take these two arrays into seperate files
So that the code is more readable.

I would put them in seperate files and call them in script.js as ES6 modules (no need to add dependencies, especially if you don't officially support IE11)
</code></pre>

**Comment by g-ravity** [comment]
I would like to take this up, if it's unassigned as of yet

**Comment by scrabill** [comment]
Hi all. The facts/costumes were part of the 2018 build BUT if you would like to port the functionality (or something similar) to the 2019 version (the current master branch), I'd be ok with that.
