### ISSUE TITLE
Enhancement: Add link to CONTRIBUTING.md to README.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#33]
Simple edit for anyone looking to practice creating pull requests. 

1. Fork the repo
2. Download all files
3. Open README.md
4. Add the following (or something similar) to README.md

`<a href="https://github.com/scrabill/how-many-days-until-halloween/blob/master/CONTRIBUTING.md">Contributing Guidelines</a>`

5. Commit change
6. Open a pull request

Questions can be asked here

**Comment by RudyB** [comment]
check #35

**Comment by scrabill** [comment]
@RudyB You have the correct link, it just needs to be on the README file not contributer-list.md. If you can make that correction I'll add that in.
