### ISSUE TITLE
Enhancement: Add link to Contributors-list.md to README.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#34]
Simple edit for anyone looking to practice creating pull requests. 

1. Fork the repo
2. Download all files
3. Open README.md
4. Add the following (or something similar) to README.md

`<a href="https://github.com/scrabill/how-many-days-until-halloween/blob/master/contributer-list.md">Contributors List</a>`

5. Commit change
6. Open a pull request

Questions can be asked here

**Comment by virenb** [comment]
I'd like to give this a try.
