### ISSUE TITLE
Update Mobile Styling

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#358]
Because of the font-size and length of the word `Halloween` the current design does not scale well on smaller screens. 

![Screen Shot 2019-10-18 at 11 05 07 PM](https://user-images.githubusercontent.com/17805262/67136945-ee620f80-f1fb-11e9-99b8-fd04bedee99c.png)

Some Ideas

- Add a media query so that the font size is scaled down appropriately on smaller screens.

**Comment by clussell** [comment]
Can I take this?

**Comment by scrabill** [comment]
@clussell Feel free to add any improvements!

**Comment by adsingh14** [comment]
@scrabill  I'm working on it !

**Comment by adsingh14** [comment]
@scrabill Have a look on [this PR](https://github.com/scrabill/how-many-days-until-halloween/pull/408). I've also curated the code and made it looking good on all mobile devices.
