### ISSUE TITLE
Update contributing document

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#360]
What I currently have on the README is very quickly going to get out of hand. I would like to have an in-depth contributing document to help contributors get started with quality submissions.

**Comment by ananya218** [comment]
I would like to work on it .

**Comment by preetilolla** [comment]
If this has not been completed, I would like to work on this issue. 

Please let me know if I can take this up.

**Comment by ananya218** [comment]
Sure...go ahead.

**Comment by imadarshj** [comment]
@scrabill  I have created a pull request see if you like it or not !

**Comment by scrabill** [comment]
A contributing doc has been added, but I am leaving this issue open if there are changes that should be made that would help to clarify for other users.

**Comment by scrabill** [comment]
Nvm, closing this issue since #361 already exists for updates.
