### ISSUE TITLE
Clarify contributing instructions

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#361]
Related to #360, I could use help coming up with clear contribution language. Perhaps, something I can use year after year. 

What I would like it to include

- How to close this repo, including which branch to focus on (the master branch)
- How to make quality contributions that are in line with the spirit of Hacktoberfest and this project
- Best practices for naming branches, refactoring, etc.
- How to avoid duplicate PRs, 'taking' someone else's idea, saving `first-timers-only` contributions for first-timers, etc

I am open to input on this and one person does not have to tackle all of what I've included above. Chime in and let's come up with something.

Chime in on this

**Comment by praveen-manick** [comment]
I would like to take this up

**Comment by alt-glitch** [comment]
I am interested in working on this. Excited for my first real contribution to open source!!
