### ISSUE TITLE
Add grid image

### ISSUE THREAD

**Issue by codeKing2020** [scrabill/how-many-days-until-halloween#375]
Added images (three) with grid display and justify-content set to space between

**Comment by LewiT-2006** [comment]
[how-many-days-until-halloween-master (1).zip](https://github.com/scrabill/how-many-days-until-halloween/files/3746655/how-many-days-until-halloween-master.1.zip)

**Comment by scrabill** [comment]
@LewiT-2006 Hello! Were you looking to add these to the README or to the website it's self?

**Comment by LewiT-2006** [comment]
You can use it for your website if you want, but basically I was doing it
for the Hacktober fest. Heard about it? It's pretty fun.
