### ISSUE TITLE
Working on issue #361

### ISSUE THREAD

**Issue by alt-glitch** [scrabill/how-many-days-until-halloween#377]
I am not sure whether this is the right place to clarify..
But as issue #361 said, you would like an instructions page for contribution, right?
I would be just writing down the pointers covering how to start with open source and pull requests and how to find and make valuable contributions and cite some sources which helped me, also a first timer, out on how to get familiar with GitHub.
Hoping you get back to me :)

**Comment by scrabill** [comment]
@alt-glitch Hey! There have been a few PRs with additions/creating a contributing doc (and some pending updates) BUT now that you say it, having a link to the contributing doc from the index.html page is a good idea. Did you want to make that update?

**Comment by alt-glitch** [comment]
Yes I would love to. I will be getting right on it in some hours after my college is over :)
