### ISSUE TITLE
Collaborative story?

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#402]
I've been thinking about this for a while. It might be fun to add a page, separate from the countdown timer, that is a collaborate story, [similar to this](https://www.fatherly.com/play/this-simple-storytelling-game-flexes-your-kids-creative-muscles/). 

Each contribution could be one line of text. Or a few. The main _rule_ would be to leave a cliffhanger for the next person to add onto. A possible topic could be a coding horror story. You know, like that time you accidentally committed broken code to the master branch 👻 

What do you all think?

**Comment by Racing5372** [comment]
I'd like to work on this issue

**Comment by mfonism** [comment]
Hi @scrabil,

Is this issue still open for Hacktoberfest 2020?

My friends will be spending a weekend at my place, and I'd like to chip this in as a fun, learning activity.

**Comment by mfonism** [comment]
Hi @scrabill,

Is this issue still open for Hacktoberfest 2020?

My friends will be spending a weekend at my place, and I'd like to chip this in as a fun, learning activity.
