### ISSUE TITLE
Enhancement: Revise JS so that only 10/31 counts as Halloween

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#5]
Currently, the logic is set up so the Halloween message will display if it is the 31st day in the month, regardless of what month it is.

Some pseudocode ideas to get you started

- Get current month
- If month is not October, then, do not display Halloween message
- If month is October, continue with existing logic

**Comment by solodynamo** [comment]
Working on this.

**Comment by arijitAD** [comment]
I will take this.

**Comment by arijitAD** [comment]
Added condition.
https://github.com/scrabill/how-many-days-until-halloween/pull/15
