### ISSUE TITLE
Documentation: Create CHANGELOG.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#52]
Since this project was posted on Github there have been several updates.

Instead of cluttering up the README.md file, the updates may be better suited in a CHANGELOG.md file. This way, updates with added features, etc, can be seen in one place. The template for the changelog can include:

- Date
- List of features added (or removed)
- Screenshot to show changes (optional)

Here's an idea of what the changelog can look like: http://keepachangelog.com/en/1.0.0/

Feel free to ask questions below before starting a pull request

**Comment by jessecalton** [comment]
Hello! Has this hacktoberfest issue been claimed yet? I'll take a stab at it!
