### ISSUE TITLE
Documentation: Move 10/18 & 10/19 updates from README.md to CHANGELOG.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#53]
#52 will need to be completed first.

Move the 10/18 and 10/19 updates to CHANGELOG.md to keep README.md from getting too cluttered.

**Comment by jessecalton** [comment]
I went ahead and submitted a PR. Cool to learn about changelogs! :)

**Comment by kaysiz** [comment]
@scrabill i do not see 10/18 in the README.md

**Comment by YendyH** [comment]
@scrabill I believe there's a grammatical (type) error in the README.md file.
I apologize as I am new to this, do I need to be added as a contributor to make a commit/pull request? I am having a hard time with this. I'm sorry if this is wrong place to put my comment. 
Thank you!!

**Comment by YendyH** [comment]
@scrabill I made a pull request for README.md.
I do see it when under the pull requests tab in "scrabill/how-many-days-until-halloween" but I can't see it under my created pull requests tab. 
Did I submit the pull request correctly? Can you see it on your end? 
I am new to this, and any feedback would be greatly appreciated. Thank you so much!

**Comment by scrabill** [comment]
Thanks for your patience everyone! I did not notice until today that I had comments on this issue.

@jessecalton Yes! I love changelogs. Here is another resource I've referenced: http://keepachangelog.com/en/0.3.0/

@kaysiz - This change has already been completed. I'll close this issue shortly.

@YendyH - Yes, I see your PR. I'll follow up there if there are any issues. Thanks!

**Comment by scrabill** [comment]
@kaysiz - I realize now that I mistyped when I said 10/18. There were only the 10/19 and 10/17 updates at the time.
