### ISSUE TITLE
Enhancement: Add more variables to splashText array

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#79]
On page load, a randomly generated string is displayed in the `<h2>` tag of index.html. We have several spooky lines of text, but there is always room for more!

To add to the array, do the following:

1. Fork the repo
2. Download all files
3. Open [spookymain.js](https://github.com/scrabill/how-many-days-until-halloween/blob/master/js/spookymain.js)
4. Starting at line 21 you will see a variable array named _splashText_
5. Within the array, add your spooky string to with the following format
`"Your Spooky Text Here",`
7. Note: The last item in the array does not need a comma
8. Commit your changes
9. Open a pull request

Beginners are more than welcome! Ask your questions below!

**Comment by GautamMandsorwale** [comment]
Hey @scrabill ,

Please check and approve this PR [https://github.com/scrabill/how-many-days-until-halloween/pull/103]

Thanks Again!

- Gautam Mandsorwale

**Comment by scrabill** [comment]
@GautamMandsorwale @mtrunt - Your additions have been merged!

**Comment by Aerisu** [comment]
I'll also add my spooky lines as well if that's alright with you @scrabill?

**Comment by zzxoto** [comment]
Hey I have never done collaboration on GIT. I have a question. So, I make some changes and push the changes to my remote repo. Then how would that get merged into this repo? Correct me if I am wrong but I have a feeling that  its has got to do with pull request. How does that work. Can some one give me full process of how the whole contribution scheme works.

**Comment by Aerisu** [comment]
@zzxoto This is a really good in-depth guide of how to properly do pull requests.
https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github
(Before I never forked, so sometimes other people's changes to the original repo would trickle down to mine.)

**Comment by Deccahedron** [comment]
Hi @scrabill,

Please see and review my Pull Request for this Issue [here.](https://github.com/scrabill/how-many-days-until-halloween/pull/142)

Happy Halloween! 👻

**Comment by arnava17** [comment]
Hi @scrabill ,

Thanks for creating this.
[Here](https://github.com/scrabill/how-many-days-until-halloween/pull/146) is my first ever Git Pull request.

Please review this.
