### ISSUE TITLE
Documentation: Create CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#80]
This project is currently lacking one.

Here is github's open source documentation on the topic:

- https://opensource.guide/code-of-conduct/

And here are other code of conduct templates/resources to reference

- http://todogroup.org/opencodeofconduct/
- https://www.contributor-covenant.org/

Overall, the code of content should hit on the following points:

- Beginners are welcome
- This is a safe place to share ideas, comments, code, etc.
- Don't be an ass

This has the potential to be a big project with some back and forth, so please, start the convo below.

**Comment by juanluischaurant** [comment]
I'ld like to work on this.

**Comment by juanluischaurant** [comment]
Done! And thank you very much.
