### ISSUE TITLE
Documentation: Add Table of Contents to README.md

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#82]
It'll be helpful to have easy to access links to commonly referenced files on the homepage 

Under the about paragraph, add links to the following pages (or any others that are relevent):

- [CHANGELOG.md](https://github.com/scrabill/how-many-days-until-halloween/blob/master/CHANGELOG.md)
- [CODE_OF_CONDUCT.md](https://github.com/scrabill/how-many-days-until-halloween/blob/master/CODE_OF_CONDUCT.md)
- [CONTRIBUTING.md](https://github.com/scrabill/how-many-days-until-halloween/blob/master/CONTRIBUTING.md)

Blurbs describing each page can be added too

**Comment by ishanyapa** [comment]
I'll take this one!
