### ISSUE TITLE
Documentation: Add PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#84]
How-to can be found here:

- https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

I'm open to thoughts on how to best structure this. To start, I think the pull request template should have the following:
- Reference to the issue, if it applies: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests
- A line or two about the proposed changes
- A prompt to add yourself to the Contributor list after your pull request has been merged

**Comment by DynamiteC** [comment]
Can I still do this?
for the first timer?

**Comment by scrabill** [comment]
@DynamiteC - This template has been created by another user, but I see some minor fixes if you would like them. 

For example, I notice the PULL_REQUEST_TEMPLATE mentions PR instead of Pull Request. If you are comfortable with it go ahead and change all instances of PR to Pull Request within this document.

Let me know if you have other questions.
