### ISSUE TITLE
Enhancement: Adjust font sizes

### ISSUE THREAD

**Issue by scrabill** [scrabill/how-many-days-until-halloween#86]
The fonts are looking a little small, especially the `<p>`. On mobile, it looks fine, but on desktop, it could use some adjusting (thing bigger, SCARIER!)

Attached is what it looks like on my 13in Macbook

![2017-10-25-23-58-](https://user-images.githubusercontent.com/17805262/32034426-85b90cae-b9e0-11e7-92be-254972fdfe75.png)

**Comment by jamie29w** [comment]
Hi all, I'm looking to help out something for the first time, and this looks fun. I see that there is a Closed badge, but I'm not sure if that means the entire issue is closed or... Anyhow, please let me know if I can still help.

**Comment by scrabill** [comment]
@jamie29w - This issue is not closed yet. Other Githubber's have made contributions, but additional changes are welcome. For example, I think the `<h1>` text can still be larger.
